In [1]:
import numpy as np

a = np.array([1., 2., 3.])
#see the size
print(np.shape(a))

(3,)


In [2]:
#change to column
#a.shape=(3, 1)
print(a)

[1. 2. 3.]


In [3]:
#print first element
print(a[0])
#print last element
print(a[-1])
#print before last element
print(a[-2])

1.0
3.0
2.0


In [4]:
print(a[1:])

[2. 3.]


In [5]:
#print the inverse
print(a[::-1])

[3. 2. 1.]


In [6]:
#see if elements of matrice are superier
print(a>1)

[False  True  True]


In [7]:
b = np.array([2.,3.,5.])
print(a*b) #produit element par element
print(a+b) #addition element par element
print(a@b) #a.t * b
print(a**2) #la puissance de tout les vecteurs

[ 2.  6. 15.]
[3. 5. 8.]
23.0
[1. 4. 9.]


In [8]:
c = np.concatenate((a, b), axis=0)
print(c)
#d = np.concatenate((a, b), axis=1)
#print(d)

[1. 2. 3. 2. 3. 5.]


In [9]:
x = np.array([1, 2, 3, 4])
print(np.var(x)) #la variance

1.25


In [10]:
print(np.sum((x - np.average(x)) ** 2)/np.shape(x)) #la variance

[1.25]


In [11]:
#x = np.array[1,2,3,4]
#x-x'(moy)= A
#<A,A> = A.T.A

k = np.subtract(x, np.average(x))
produit =(k.shape(4,1)*k)/np.shape(x)
print(produit)
print(a@k)

TypeError: 'tuple' object is not callable

In [12]:
y = np.arange(1,11)
print(y)
z = np.random.randint(1,11, size=6)
print(z)
v = np.random.randn()

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  8  2  3 10 10]


In [13]:
z = np.argsort(z)
print(z)
z = np.sort(-z)
print(z)

[2 0 3 1 4 5]
[-5 -4 -3 -2 -1  0]


In [14]:
r  = np.zeros(5)
print(r)
o = np.ones(4)
print(o)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
