In [101]:
import numpy as np

a = np.array([1., 2., 3.])
#see the size
print(np.shape(a))

(3,)


In [102]:
#change to column
#a.shape=(3, 1)
print(a)

[1. 2. 3.]


In [103]:
#print first element
print(a[0])
#print last element
print(a[-1])
#print before last element
print(a[-2])

1.0
3.0
2.0


In [104]:
print(a[1:])

[2. 3.]


In [105]:
#print the inverse
print(a[::-1])

[3. 2. 1.]


In [106]:
#see if elements of matrice are superier
print(a>1)

[False  True  True]


In [107]:
b = np.array([2.,3.,5.])
print(a*b) #produit element par element
print(a+b) #addition element par element
print(a@b) #a.t * b
print(a**2) #la puissance de tout les vecteurs

[ 2.  6. 15.]
[3. 5. 8.]
23.0
[1. 4. 9.]


In [108]:
c = np.concatenate((a, b), axis=0)
print(c)
#d = np.concatenate((a, b), axis=1)
#print(d)

[1. 2. 3. 2. 3. 5.]


In [109]:
x = np.array([1, 2, 3, 4])
print(np.var(x)) #la variance

1.25


In [116]:
print(np.sum((x - np.average(x)) ** 2)/np.shape(x)) #la variance

[1.25]


In [123]:
#x = np.array[1,2,3,4]
#x-x'(moy)= A
#<A,A> = A.T.A

k = np.subtract(x, np.average(x))
produit =(k.shape(4,1)*k)/np.shape(x)
print(produit)
print(a@k)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [131]:
y = np.arange(1,11)
print(y)
z = np.random.randint(1,11, size=10)
print(z)
v = np.random.randn()

[ 1  2  3  4  5  6  7  8  9 10]
[5 4 9 7 6 7 1 5 2 3]
