In [410]:
#importing stuff
import numpy as np
import pandas as pd 

In [411]:
print(" Notre Matrice:")
exp = np.array([["bleu", "lourd", "rond"],
                ["blanc", "leger", "carre"],
                ["vert", "leger", "rond"],
                ["bleu", "tres lourd", "carre"],
                ["blanc", "leger", "rond"],
                ["vert", "tres lourd", "carre"],
                ["bleu", "leger", "rond"],
                ["blanc", "tres lourd", "carre"],
                ["vert", "tres lourd", "rond"],
                ["bleu", "lourd", "carre"],
                ])
columns = ["Couleur", "Poids", "Forme"]
df = pd.DataFrame(data=exp, columns=columns)
display(df)

 Notre Matrice:


Couleur       Poids  Forme
0    bleu       lourd   rond
1   blanc       leger  carre
2    vert       leger   rond
3    bleu  tres lourd  carre
4   blanc       leger   rond
5    vert  tres lourd  carre
6    bleu       leger   rond
7   blanc  tres lourd  carre
8    vert  tres lourd   rond
9    bleu       lourd  carre

In [412]:
print(" ====> Etape 1: Les Tableaux de contingences:\n")
cont = []
no_repeat = []
for i in columns:
    for j in columns:
        if i != j:
            if [j, i] not in no_repeat:
                print(pd.crosstab(index=df[i], columns=df[j]), "\n\n")
                cont.append(pd.crosstab(index=df[i], columns=df[j]))
                no_repeat.append([i, j])

 ====> Etape 1: Les Tableaux de contingences:

Poids    leger  lourd  tres lourd
Couleur                          
blanc        2      0           1
bleu         1      2           1
vert         1      0           2 


Forme    carre  rond
Couleur             
blanc        2     1
bleu         2     2
vert         1     2 


Forme       carre  rond
Poids                  
leger           1     3
lourd           1     1
tres lourd      3     1 




In [413]:
print(" ====> Etape 2: Tableau de frequence fij\n")
freq = []
for i in cont:
    i = i / df.shape[0]
    freq.append(i)
for i in freq:
    i['Total'] = i.sum(axis=1)
    i.loc["Total"] = i.sum()
    print(i, "\n\n")

 ====> Etape 2: Tableau de frequence fij

Poids    leger  lourd  tres lourd  Total
Couleur                                 
blanc      0.2    0.0         0.1    0.3
bleu       0.1    0.2         0.1    0.4
vert       0.1    0.0         0.2    0.3
Total      0.4    0.2         0.4    1.0 


Forme    carre  rond  Total
Couleur                    
blanc      0.2   0.1    0.3
bleu       0.2   0.2    0.4
vert       0.1   0.2    0.3
Total      0.5   0.5    1.0 


Forme       carre  rond  Total
Poids                         
leger         0.1   0.3    0.4
lourd         0.1   0.1    0.2
tres lourd    0.3   0.1    0.4
Total         0.5   0.5    1.0 




In [414]:
print(" ====> Etape 3: Tableau de profils ligne \n")
fij = []
count = 0
for i in freq:
    if count < i.shape[0]:
        i = i / i['Total'][count]
        count += 1
        fij.append(i)
for i in fij:
    print(i, "\n")


 ====> Etape 3: Tableau de profils ligne 

Poids       leger     lourd  tres lourd     Total
Couleur                                          
blanc    0.666667  0.000000    0.333333  1.000000
bleu     0.333333  0.666667    0.333333  1.333333
vert     0.333333  0.000000    0.666667  1.000000
Total    1.333333  0.666667    1.333333  3.333333 

Forme    carre  rond  Total
Couleur                    
blanc     0.50  0.25   0.75
bleu      0.50  0.50   1.00
vert      0.25  0.50   0.75
Total     1.25  1.25   2.50 

Forme       carre  rond  Total
Poids                         
leger        0.25  0.75    1.0
lourd        0.25  0.25    0.5
tres lourd   0.75  0.25    1.0
Total        1.25  1.25    2.5 



In [415]:
print(" ====> Etape 4: Tableau de profils colonnes \n")
fji = []
count = 0
for i in freq:
    if count < i.shape[0]:
        i = i / i.loc['Total'][count]
        count += 1
        fji.append(i)
for i in fji:
    print(i, "\n")

 ====> Etape 4: Tableau de profils colonnes 

Poids    leger  lourd  tres lourd  Total
Couleur                                 
blanc     0.50    0.0        0.25   0.75
bleu      0.25    0.5        0.25   1.00
vert      0.25    0.0        0.50   0.75
Total     1.00    0.5        1.00   2.50 

Forme    carre  rond  Total
Couleur                    
blanc      0.4   0.2    0.6
bleu       0.4   0.4    0.8
vert       0.2   0.4    0.6
Total      1.0   1.0    2.0 

Forme       carre  rond  Total
Poids                         
leger         0.1   0.3    0.4
lourd         0.1   0.1    0.2
tres lourd    0.3   0.1    0.4
Total         0.5   0.5    1.0 



In [416]:
print("La Metrique de i:")
mi = []
for i in freq:
    m = np.zeros((len(i["Total"]) - 1, len(i["Total"]) - 1), float)
    l = []
    for k in range(len(i["Total"]) - 1):
        l.append(i['Total'][k])
    for i in range(len(l)):
        m[i, i] = 1/l[i]
    mi.append(m)
count = 0
for j in mi:
    count += 1
    print("Pour Tableau " + str(count))
    print(j, "\n")


La Metrique de i:
Pour Tableau 1
[[3.33333333 0.         0.        ]
 [0.         2.5        0.        ]
 [0.         0.         3.33333333]] 

Pour Tableau 2
[[3.33333333 0.         0.        ]
 [0.         2.5        0.        ]
 [0.         0.         3.33333333]] 

Pour Tableau 3
[[2.5 0.  0. ]
 [0.  5.  0. ]
 [0.  0.  2.5]] 



In [417]:
print("La Metrique de j:")
mj = []
for i in freq:
    m = np.zeros((len(i.loc["Total"]) - 1, len(i.loc["Total"]) - 1), float)
    l = []
    for k in range(len(i.loc["Total"]) - 1):
        l.append(i.loc['Total'][k])
    for i in range(len(l)):
        m[i, i] = 1/l[i]
    mj.append(m)
count = 0
for j in mj:
    count += 1
    print("Pour Tableau " + str(count))
    print(j, "\n")

La Metrique de j:
Pour Tableau 1
[[2.5 0.  0. ]
 [0.  5.  0. ]
 [0.  0.  2.5]] 

Pour Tableau 2
[[2. 0.]
 [0. 2.]] 

Pour Tableau 3
[[2. 0.]
 [0. 2.]] 



In [418]:
print(" ====> Etape 5: Calculer X :\n")
X = []
for i in freq:
    for j in range(len(mi)):
        x = mi[j]**(-1/2) @ (0.2 - i["Total"].iloc[:-1:].T @ i.loc["Total"].iloc[:-1:].T) @ mj[j]**(-1/2)
    X.append(x)
print(X)

 ====> Etape 5: Calculer X :

Poids    leger  lourd  tres lourd  Total
Couleur                                 
blanc      0.2    0.0         0.1    0.3
bleu       0.1    0.2         0.1    0.4
vert       0.1    0.0         0.2    0.3
Total      0.4    0.2         0.4    1.0


C:\Users\YOGA\AppData\Local\Temp\ipykernel_10820\1660410510.py:6: RuntimeWarning: divide by zero encountered in power
  x = mi[j]**(-1/2) @ (0.2 - i["Total"].iloc[:-1:].T @ i.loc["Total"].iloc[:-1:].T) @ mj[j]**(-1/2)


ValueError: matrices are not aligned